{
 "title": "Glusterfs Dashboard",
 "description": "Dashboard based on glusterfs official collector (https://github.com/gluster/gluster-prometheus)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "volume",
    "label": "数据卷",
    "query": "label_values(gluster_volume_status,volume)"
   },
   {
    "name": "hostname",
    "label": "主机",
    "query": "label_values(gluster_brick_connected,hostname)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({job=\"glusterfs\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "gluster cluster status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(gluster_node_size_free_bytes{hostname=\"192.168.20.46\"}) / max(gluster_volumes_available)",
     "legendFormat": "192.168.20.46"
    },
    {
     "expr": "count(gluster_node_size_free_bytes{hostname=\"192.168.20.47\"}) / max(gluster_volumes_available)",
     "legendFormat": "192.168.20.47"
    },
    {
     "expr": "count(gluster_node_size_free_bytes{hostname=\"192.168.20.48\"}) / max(gluster_volumes_available)",
     "legendFormat": "192.168.20.48"
    }
   ]
  },
  {
   "title": "gluster_volume_status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gluster_volume_status", "legendFormat": "volume:  {{volume}}" }
   ]
  },
  {
   "title": "gluster_volume_count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(gluster_volume_status)" }
   ]
  },
  {
   "title": "gluster_cpu_percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"glusterfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gluster_memory_percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"glusterfs\"}"
    }
   ]
  },
  {
   "title": "gluster_subvol_capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_sys_bytes{instance=\"20-46-glusterfs\"}"
    }
   ]
  },
  {
   "title": "GlusterFS Volume 剩余容量  $volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "gluster_node_size_free_bytes{instance=\"20-46-glusterfs\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "gluster_brick_inodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gluster_brick_available", "legendFormat": "{{volume}}" }
   ]
  },
  {
   "title": "gluster_virtual_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"glusterfs\"}"
    }
   ]
  },
  {
   "title": "gluster_resident_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"glusterfs\"}"
    }
   ]
  },
  {
   "title": "gluster_peers_connected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gluster_peers_connected" }
   ]
  }
 ]
}